/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthAiRouteImport } from './routes/_auth.ai'
import { Route as AuthConsentRouteImport } from './routes/_auth.consent'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthLiteracyRouteImport } from './routes/_auth.literacy'
import { Route as AuthLoansRouteImport } from './routes/_auth.loans'
import { Route as AuthMoneyRouteImport } from './routes/_auth.money'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthRecommendationsRouteImport } from './routes/_auth.recommendations'
import { Route as AuthWellnessRouteImport } from './routes/_auth.wellness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAiRoute = AuthAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLiteracyRoute = AuthLiteracyRouteImport.update({
  id: '/literacy',
  path: '/literacy',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansRoute = AuthLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMoneyRoute = AuthMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecommendationsRoute = AuthRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWellnessRoute = AuthWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/ai': typeof AuthAiRoute
  '/consent': typeof AuthConsentRoute
  '/dashboard': typeof AuthDashboardRoute
  '/literacy': typeof AuthLiteracyRoute
  '/loans': typeof AuthLoansRoute
  '/money': typeof AuthMoneyRoute
  '/profile': typeof AuthProfileRoute
  '/recommendations': typeof AuthRecommendationsRoute
  '/wellness': typeof AuthWellnessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/ai': typeof AuthAiRoute
  '/consent': typeof AuthConsentRoute
  '/dashboard': typeof AuthDashboardRoute
  '/literacy': typeof AuthLiteracyRoute
  '/loans': typeof AuthLoansRoute
  '/money': typeof AuthMoneyRoute
  '/profile': typeof AuthProfileRoute
  '/recommendations': typeof AuthRecommendationsRoute
  '/wellness': typeof AuthWellnessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_auth/ai': typeof AuthAiRoute
  '/_auth/consent': typeof AuthConsentRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/literacy': typeof AuthLiteracyRoute
  '/_auth/loans': typeof AuthLoansRoute
  '/_auth/money': typeof AuthMoneyRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/recommendations': typeof AuthRecommendationsRoute
  '/_auth/wellness': typeof AuthWellnessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/ai'
    | '/consent'
    | '/dashboard'
    | '/literacy'
    | '/loans'
    | '/money'
    | '/profile'
    | '/recommendations'
    | '/wellness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/ai'
    | '/consent'
    | '/dashboard'
    | '/literacy'
    | '/loans'
    | '/money'
    | '/profile'
    | '/recommendations'
    | '/wellness'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_auth/ai'
    | '/_auth/consent'
    | '/_auth/dashboard'
    | '/_auth/literacy'
    | '/_auth/loans'
    | '/_auth/money'
    | '/_auth/profile'
    | '/_auth/recommendations'
    | '/_auth/wellness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/ai': {
      id: '/_auth/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthAiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/consent': {
      id: '/_auth/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/literacy': {
      id: '/_auth/literacy'
      path: '/literacy'
      fullPath: '/literacy'
      preLoaderRoute: typeof AuthLiteracyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans': {
      id: '/_auth/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthLoansRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/money': {
      id: '/_auth/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthMoneyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recommendations': {
      id: '/_auth/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthRecommendationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/wellness': {
      id: '/_auth/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AuthWellnessRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAiRoute: typeof AuthAiRoute
  AuthConsentRoute: typeof AuthConsentRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLiteracyRoute: typeof AuthLiteracyRoute
  AuthLoansRoute: typeof AuthLoansRoute
  AuthMoneyRoute: typeof AuthMoneyRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthRecommendationsRoute: typeof AuthRecommendationsRoute
  AuthWellnessRoute: typeof AuthWellnessRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAiRoute: AuthAiRoute,
  AuthConsentRoute: AuthConsentRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLiteracyRoute: AuthLiteracyRoute,
  AuthLoansRoute: AuthLoansRoute,
  AuthMoneyRoute: AuthMoneyRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRecommendationsRoute: AuthRecommendationsRoute,
  AuthWellnessRoute: AuthWellnessRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
